### ISSUE TITLE
Issue With Detecting

### ISSUE THREAD

**Issue by qkrtjdus0805** [H0JunP/Term-Project#4]
When launched, program displays 'No Mask' when there's person with mask on, and program displays 'Mask' when there's person with mask off.
<img width="961" alt="KakaoTalk_Photo_2023-12-08-14-58-46" src="https://github.com/H0JunP/Term-Project/assets/144338172/34be6f79-aefd-4285-9726-faa26f05438e">

**Comment by H0JunP** [comment]
Fixed issue, and updated source code FaceMaskDetection_Updated.py to reflect the changes.
